version: '3.4'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"

  api:
    build: ./backend
    volumes:
      - ./backend:/api
    depends_on:
      - db
    ports:
      - "5000:5000"
    command: npm start
    environment:
      NODE_ENV: development


  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
